### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by photobuff99** [Clacious/Uhlar_CSCI2270_FinalProject#1]
There is no make file and I don't know what order to compile all of the files in.  I don't want to give a bad score, please get back to me with instructions on how to compile.

**Comment by Clacious** [comment]
Ok, I tried to reformat the folder to make it easier!

If you git clone this repo to your machine you will download the Uhlar_CSCI2270_FinalProject folder.
Inside of that folder is another folder called Final.
Final contains all the files needed to run the program.

One way to run it is to open the Final.cbp through an IDE, such as code blocks. the IDE compiler has to be set to follow c++ 11 ISO. To set the compiler in codeblocks go to:

settings >>compiler >> global compiler settings >> then check "have g++ follow c++11 ISO c++ language ..."

If this does not work you can also compile all the .cpp and .h files via the terminal. make sure that when compiling all the files to start with "g++ -std=c++11"  before typing the files.

Lastly, make sure the .txt files (NFL_2014_PLAYERS_OFFENSE.txt and NFL_2014_TEAMS_OFFENSE.txt) are located in the directory you are working in.

Sorry i took a while to respond, I accidentally deleted my project from the repo and had to figure out how to restore it.

Hope this helps!

**Comment by photobuff99** [comment]
It compiles now

**Comment by photobuff99** [comment]
Closes #1
